---
- name: ensure fluentd dirs
  file:
    dest: '{{ item }}'
    state: directory
  with_items:
    - '{{ fluentd_dir }}'
    - '{{ fluentd_log_dir }}'
    - '{{ fluentd_buffer_dir }}'

- name: ensure fluentd config
  template:
    src: fluent.conf.j2
    dest: '{{ fluentd_dir }}/fluent.conf'
    force: yes

- name: run fluentd_logger container
  docker_container:
    state: started
    restart: yes
    recreate: yes
    pull: true
    name: '{{ fluentd_container_name }}'
    image: '{{ fluentd_image }}'
    restart_policy: always
    published_ports: '{{ fluentd_published_ports }}'
    links: '{{ fluentd_links }}'
    networks: '{{ fluentd_networks }}'
    volumes: '{{ fluentd_volumes }}'
    env: '{{ fluentd_env }}'
